version: '3'
services:
  # frontend:
  #   build: ./
  #   container_name: frontend
  #   ports:
  #     - '3000:3000'

  dev-db:
    container_name: bulletin-board-postgres
    image: postgres:14
    ports:
      - '5432:5432'
    # volumes:
    #   - ~/data/postgres:/data/postgres
    env_file: .env
    networks:
      - postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: myS3cr3tp@ssw0rd

  # pgadmin:
  #   links:
  #     - dev-db:dev-db
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   ports:
  #     - '8080:80'
  #   volumes:
  #     - ~/data/pgadmin:/root/.pgadmin
  #   env_file: .env
  #   networks:
  #     - postgres
networks:
  postgres:
    driver: bridge
