version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - '9000:9000'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db
    command: yarn start:dev

  db:
    container_name: ${POSTGRES_CONTAINER}
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
